### ISSUE TITLE
Only 1 slice converted

### ISSUE THREAD

**Issue by annewiet** [amine0110/Medical-Conversions#1]
Hi! Thank you for making this GUI!

I am trying to convert a nifti image to a dicom series. I have accessed the GUI and clicked 'convert & save' and see that it's 'Converting...' However, I have been waiting for about 30 min now and only slice0000 has been created (instantly after starting) Is that normal? How long is it expected to take to convert a single file?

Thanks for the help!

**Comment by davidcellams** [comment]
I had a similar issue @annewiet . An error was thrown in the console execution:

"ITK ERROR: GDCMImageIO(00000261FD88AA00): A Floating point buffer was passed but the stored pixel type was not specified.This is currently not supported"

SOLUTION:
Modify the convert_nifti_to_dicom function. Just specify in the ReadImage function the datatype integer16. DICOM images conversion for ITK do not support other format, otherwise the mentioned error will show up and stop the execution. Just add the following in the first line of the function.
-->      new_img = sitk.ReadImage(in_dir, sitk.sitkInt16)

Hope it helps!
